name: HealthBridge
description: "A new HealthBridge project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Phone Number Input
#  intl_phone_field: ^3.2.0
#  country_code_picker: ^3.0.0

  # UI Components
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  table_calendar: ^3.1.2

  # Navigation
  go_router: ^14.2.0
  url_launcher: ^6.3.1

  # SVG Support
  flutter_svg: ^2.0.10+1

  # Image Picker & Upload
  image_picker: ^1.0.7
  http: ^1.2.1
  path_provider: ^2.1.2

  # Notifications & File Opening
  flutter_local_notifications: ^17.2.3
  open_filex: ^4.5.0
  permission_handler: ^11.3.1

  # Payment
#  flutter_stripe: 11.1.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
#    - assets/images/patient.png

